//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// This code was generated by XmlSchemaClassGenerator version 2.0.425.0.
namespace DeveReproduceXmlSerializerBug.Tests.TestModels
{
    using System.Collections;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.Xml.Serialization;

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedAccountDirectionTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedAccountDirectionTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedAccountDirectionTypeList
    {

        ZPD,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedAccountTypeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedAccountTypeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedAccountTypeTypeList
    {

        ZOC,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedBusinessTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedBusinessTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedBusinessTypeList
    {

        [System.Xml.Serialization.XmlEnumAttribute("12G")]
        Item12G,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedCharacteristicTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedCharacteristicTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedCharacteristicTypeList
    {

        Y,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedCodingSchemeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedCodingSchemeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedCodingSchemeTypeList
    {

        [System.Xml.Serialization.XmlEnumAttribute("305")]
        Item305,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedCurrencyTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedCurrencyTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedCurrencyTypeList
    {

        EUR,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedDocumentTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedDocumentTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedDocumentTypeList
    {

        [System.Xml.Serialization.XmlEnumAttribute("01G")]
        Item01G,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedGasDirectionTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedGasDirectionTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedGasDirectionTypeList
    {

        Z02,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedIndicatorTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedIndicatorTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedIndicatorTypeList
    {

        [System.Xml.Serialization.XmlEnumAttribute("01G")]
        Item01G,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedSpanTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedSpanTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedSpanTypeList
    {

        ZEJ,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedMeasurementTypeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedMeasurementTypeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedMeasurementTypeTypeList
    {

        [System.Xml.Serialization.XmlEnumAttribute("3B")]
        Item3B,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedNominationTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedNominationTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedNominationTypeList
    {

        A01,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedQuantityNatureTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedQuantityNatureTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedQuantityNatureTypeList
    {

        Z01,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedQuantityTypeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedQuantityTypeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedQuantityTypeTypeList
    {

        ZXD,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedReasonCodeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedReasonCodeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedReasonCodeTypeList
    {

        [System.Xml.Serialization.XmlEnumAttribute("01G")]
        Item01G,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedReferenceTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedReferenceTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedReferenceTypeList
    {

        ACW,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedRoleTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedRoleTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedRoleTypeList
    {

        ZSO,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedStatusCategoryTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedStatusCategoryTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedStatusCategoryTypeList
    {

        [System.Xml.Serialization.XmlEnumAttribute("04G")]
        Item04G,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedStatusTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedStatusTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedStatusTypeList
    {

        [System.Xml.Serialization.XmlEnumAttribute("03G")]
        Item03G,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocalRestrictedUnitOfMeasureTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("LocalRestrictedUnitOfMeasureTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum LocalRestrictedUnitOfMeasureTypeList
    {

        KW1,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("TsoCodingSchemeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("TsoCodingSchemeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum TsoCodingSchemeTypeList
    {

        ZSO,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("EicCodingSchemeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("EicCodingSchemeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum EicCodingSchemeTypeList
    {

        [System.Xml.Serialization.XmlEnumAttribute("305")]
        Item305,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StandardRestrictedCodingSchemeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("StandardRestrictedCodingSchemeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum StandardRestrictedCodingSchemeTypeList
    {

        [System.Xml.Serialization.XmlEnumAttribute("305")]
        Item305,

        ZSO,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("CodingSchemeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("CodingSchemeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum CodingSchemeTypeList
    {

        [System.Xml.Serialization.XmlEnumAttribute("305")]
        Item305,

        ZSO,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StandardRestrictedDocumentTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("StandardRestrictedDocumentTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum StandardRestrictedDocumentTypeList
    {

        [System.Xml.Serialization.XmlEnumAttribute("01G")]
        Item01G,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("DocumentTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("DocumentTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum DocumentTypeList
    {

        [System.Xml.Serialization.XmlEnumAttribute("01G")]
        Item01G,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StandardRestrictedGasDirectionTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("StandardRestrictedGasDirectionTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum StandardRestrictedGasDirectionTypeList
    {

        Z02,

        Z03,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("GasDirectionTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("GasDirectionTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum GasDirectionTypeList
    {

        Z02,

        Z03,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StandardRestrictedNominationTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("StandardRestrictedNominationTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum StandardRestrictedNominationTypeList
    {

        A01,

        A02,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NominationTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("NominationTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum NominationTypeList
    {

        A01,

        A02,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StandardRestrictedQuantityTypeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("StandardRestrictedQuantityTypeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum StandardRestrictedQuantityTypeTypeList
    {

        ZXD,

        ZXE,

        ZXF,

        ZXG,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("QuantityTypeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("QuantityTypeTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum QuantityTypeTypeList
    {

        ZXD,

        ZXE,

        ZXF,

        ZXG,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("IssuerRoleTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("IssuerRoleTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum IssuerRoleTypeList
    {

        ZSH,

        ZSY,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RecipientRoleTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("RecipientRoleTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum RecipientRoleTypeList
    {

        ZSO,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StandardRestrictedRoleTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("StandardRestrictedRoleTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum StandardRestrictedRoleTypeList
    {

        ZSH,

        ZSY,

        ZSO,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("RoleTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("RoleTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum RoleTypeList
    {

        ZSH,

        ZSY,

        ZSO,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("StandardRestrictedUnitOfMeasureTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("StandardRestrictedUnitOfMeasureTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum StandardRestrictedUnitOfMeasureTypeList
    {

        KW1,

        KW2,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("UnitOfMeasureTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Xml.Serialization.XmlRootAttribute("UnitOfMeasureTypeList", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public enum UnitOfMeasureTypeList
    {

        KW1,

        KW2,
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("AccountType", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("AccountType", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public partial class AccountType
    {

        /// <summary>
        /// <para xml:lang="de">Ruft den Text ab oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("codingScheme")]
        public CodingSchemeTypeList CodingScheme { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("PartyType", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("PartyType", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public partial class PartyType
    {

        /// <summary>
        /// <para xml:lang="de">Ruft den Text ab oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("codingScheme")]
        public CodingSchemeTypeList CodingScheme { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Account", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Account", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public partial class Account
    {

        [System.Xml.Serialization.XmlElementAttribute("internalAccount")]
        public AccountType InternalAccount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("internalAccountTso")]
        public PartyType InternalAccountTso { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("externalAccount")]
        public AccountType ExternalAccount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("externalAccountTso")]
        public PartyType ExternalAccountTso { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Period> _period;

        [System.Xml.Serialization.XmlElementAttribute("Period")]
        public System.Collections.ObjectModel.Collection<Period> Period
        {
            get
            {
                return this._period;
            }
            private set
            {
                this._period = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="Account" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Account" /> class.</para>
        /// </summary>
        public Account()
        {
            this._period = new System.Collections.ObjectModel.Collection<Period>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Period", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Period", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public partial class Period
    {

        /// <summary>
        /// <para xml:lang="en">Pattern: (((((20[0-9]{2})[\-](0[13578]|1[02])[\-](0[1-9]|[12][0-9]|3[01])|([0-9]{4})[\-]((0[469])|(11))[\-](0[1-9]|[12][0-9]|30))T(([01][0-9]|2[0-3]):[0-5][0-9])Z/)|(([13579][26][02468][048]|[13579][01345789](0)[48]|[13579][01345789][2468][048]|[02468][048][02468][048]|[02468][1235679](0)[48]|[02468][1235679][2468][048]|[0-9][0-9][13579][26])[\-](02)[\-](0[1-9]|1[0-9]|2[0-9])T(([01][0-9]|2[0-3]):[0-5][0-9])Z/)|(([13579][26][02468][1235679]|[13579][01345789](0)[01235679]|[13579][01345789][2468][1235679]|[02468][048][02468][1235679]|[02468][1235679](0)[01235679]|[02468][1235679][2468][1235679]|[0-9][0-9][13579][01345789])[\-](02)[\-](0[1-9]|1[0-9]|2[0-8])T(([01][0-9]|2[0-3]):[0-5][0-9])Z/))(((([0-9]{4})-(0[13578]|1[02])[\-](0[1-9]|[12][0-9]|3[01])|([0-9]{4})[\-]((0[469])|(11))[\-](0[1-9]|[12][0-9]|30))T(([01][0-9]|2[0-3]):[0-5][0-9])Z)|(([13579][26][02468][048]|[13579][01345789](0)[48]|[13579][01345789][2468][048]|[02468][048][02468][048]|[02468][1235679](0)[48]|[02468][1235679][2468][048]|[0-9][0-9][13579][26])[\-](02)[\-](0[1-9]|1[0-9]|2[0-9])T(([01][0-9]|2[0-3]):[0-5][0-9])Z)|(([13579][26][02468][1235679]|[13579][01345789](0)[01235679]|[13579][01345789][2468][1235679]|[02468][048][02468][1235679]|[02468][1235679](0)[01235679]|[02468][1235679][2468][1235679]|[0-9][0-9][13579][01345789])[\-](02)[\-](0[1-9]|1[0-9]|2[0-8])T(([01][0-9]|2[0-3]):[0-5][0-9])Z))).</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute(@"(((((20[0-9]{2})[\-](0[13578]|1[02])[\-](0[1-9]|[12][0-9]|3[01])|([0-9]{4})[\-]((0[469])|(11))[\-](0[1-9]|[12][0-9]|30))T(([01][0-9]|2[0-3]):[0-5][0-9])Z/)|(([13579][26][02468][048]|[13579][01345789](0)[48]|[13579][01345789][2468][048]|[02468][048][02468][048]|[02468][1235679](0)[48]|[02468][1235679][2468][048]|[0-9][0-9][13579][26])[\-](02)[\-](0[1-9]|1[0-9]|2[0-9])T(([01][0-9]|2[0-3]):[0-5][0-9])Z/)|(([13579][26][02468][1235679]|[13579][01345789](0)[01235679]|[13579][01345789][2468][1235679]|[02468][048][02468][1235679]|[02468][1235679](0)[01235679]|[02468][1235679][2468][1235679]|[0-9][0-9][13579][01345789])[\-](02)[\-](0[1-9]|1[0-9]|2[0-8])T(([01][0-9]|2[0-3]):[0-5][0-9])Z/))(((([0-9]{4})-(0[13578]|1[02])[\-](0[1-9]|[12][0-9]|3[01])|([0-9]{4})[\-]((0[469])|(11))[\-](0[1-9]|[12][0-9]|30))T(([01][0-9]|2[0-3]):[0-5][0-9])Z)|(([13579][26][02468][048]|[13579][01345789](0)[48]|[13579][01345789][2468][048]|[02468][048][02468][048]|[02468][1235679](0)[48]|[02468][1235679][2468][048]|[0-9][0-9][13579][26])[\-](02)[\-](0[1-9]|1[0-9]|2[0-9])T(([01][0-9]|2[0-3]):[0-5][0-9])Z)|(([13579][26][02468][1235679]|[13579][01345789](0)[01235679]|[13579][01345789][2468][1235679]|[02468][048][02468][1235679]|[02468][1235679](0)[01235679]|[02468][1235679][2468][1235679]|[0-9][0-9][13579][01345789])[\-](02)[\-](0[1-9]|1[0-9]|2[0-8])T(([01][0-9]|2[0-3]):[0-5][0-9])Z)))")]
        [System.Xml.Serialization.XmlElementAttribute("timeInterval")]
        public string TimeInterval { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("direction.code")]
        public string DirectionPeriodCode { get; set; }

        /// <summary>
        /// <para xml:lang="en">Total number of digits: 17.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("quantity.amount")]
        public decimal QuantityPeriodAmount { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("priority_Status.code")]
        public string Priority_StatusPeriodCode { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Decomposition_Quantity> _decomposition_Quantity;

        [System.Xml.Serialization.XmlElementAttribute("Decomposition_Quantity")]
        public System.Collections.ObjectModel.Collection<Decomposition_Quantity> Decomposition_Quantity
        {
            get
            {
                return this._decomposition_Quantity;
            }
            private set
            {
                this._decomposition_Quantity = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Ruft einen Wert ab, der angibt, ob die Decomposition_Quantity-Collection leer ist.</para>
        /// <para xml:lang="en">Gets a value indicating whether the Decomposition_Quantity collection is empty.</para>
        /// </summary>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool Decomposition_QuantitySpecified
        {
            get
            {
                return (this.Decomposition_Quantity.Count != 0);
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="Period" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Period" /> class.</para>
        /// </summary>
        public Period()
        {
            this._decomposition_Quantity = new System.Collections.ObjectModel.Collection<Decomposition_Quantity>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Decomposition_Quantity", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Decomposition_Quantity", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public partial class Decomposition_Quantity
    {

        [System.Xml.Serialization.XmlElementAttribute("type")]
        public string Type { get; set; }

        /// <summary>
        /// <para xml:lang="en">Total number of digits: 17.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("amount")]
        public decimal Amount { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("MeasurementPointType", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("MeasurementPointType", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public partial class MeasurementPointType
    {

        /// <summary>
        /// <para xml:lang="de">Ruft den Text ab oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("codingScheme")]
        public CodingSchemeTypeList CodingScheme { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("ConnectionPoint", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("ConnectionPoint", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public partial class ConnectionPoint
    {

        [System.Xml.Serialization.XmlElementAttribute("identification")]
        public MeasurementPointType Identification { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("measureUnit.code")]
        public string MeasureUnitPeriodCode { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<NominationType> _nominationType;

        [System.Xml.Serialization.XmlElementAttribute("NominationType")]
        public System.Collections.ObjectModel.Collection<NominationType> NominationType
        {
            get
            {
                return this._nominationType;
            }
            private set
            {
                this._nominationType = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="ConnectionPoint" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="ConnectionPoint" /> class.</para>
        /// </summary>
        public ConnectionPoint()
        {
            this._nominationType = new System.Collections.ObjectModel.Collection<NominationType>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("NominationType", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("NominationType", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public partial class NominationType
    {

        [System.Xml.Serialization.XmlElementAttribute("type")]
        public string Type { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<Account> _account;

        [System.Xml.Serialization.XmlElementAttribute("Account")]
        public System.Collections.ObjectModel.Collection<Account> Account
        {
            get
            {
                return this._account;
            }
            private set
            {
                this._account = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="NominationType" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="NominationType" /> class.</para>
        /// </summary>
        public NominationType()
        {
            this._account = new System.Collections.ObjectModel.Collection<Account>();
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("LocationType", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("LocationType", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public partial class LocationType
    {

        /// <summary>
        /// <para xml:lang="de">Ruft den Text ab oder legt diesen fest.</para>
        /// <para xml:lang="en">Gets or sets the text value.</para>
        /// </summary>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value { get; set; }

        [System.Xml.Serialization.XmlAttributeAttribute("codingScheme")]
        public CodingSchemeTypeList CodingScheme { get; set; }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("XmlSchemaClassGenerator", "2.0.425.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute("Nomination_Document", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlRootAttribute("Nomination_Document", Namespace = "urn:test.eu:blah:testtest123:document:5:1")]
    public partial class Nomination_Document
    {

        /// <summary>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(35)]
        [System.Xml.Serialization.XmlElementAttribute("identification")]
        public string Identification { get; set; }

        /// <summary>
        /// <para xml:lang="en">Maximum inclusive value: 999.</para>
        /// </summary>
        [System.Xml.Serialization.XmlElementAttribute("version")]
        public string Version { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("type")]
        public string Type { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("creationDateTime", DataType = "dateTime")]
        public System.DateTime CreationDateTime { get; set; }

        /// <summary>
        /// <para xml:lang="en">Pattern: (((((20[0-9]{2})[\-](0[13578]|1[02])[\-](0[1-9]|[12][0-9]|3[01])|([0-9]{4})[\-]((0[469])|(11))[\-](0[1-9]|[12][0-9]|30))T(([01][0-9]|2[0-3]):[0-5][0-9])Z/)|(([13579][26][02468][048]|[13579][01345789](0)[48]|[13579][01345789][2468][048]|[02468][048][02468][048]|[02468][1235679](0)[48]|[02468][1235679][2468][048]|[0-9][0-9][13579][26])[\-](02)[\-](0[1-9]|1[0-9]|2[0-9])T(([01][0-9]|2[0-3]):[0-5][0-9])Z/)|(([13579][26][02468][1235679]|[13579][01345789](0)[01235679]|[13579][01345789][2468][1235679]|[02468][048][02468][1235679]|[02468][1235679](0)[01235679]|[02468][1235679][2468][1235679]|[0-9][0-9][13579][01345789])[\-](02)[\-](0[1-9]|1[0-9]|2[0-8])T(([01][0-9]|2[0-3]):[0-5][0-9])Z/))(((([0-9]{4})-(0[13578]|1[02])[\-](0[1-9]|[12][0-9]|3[01])|([0-9]{4})[\-]((0[469])|(11))[\-](0[1-9]|[12][0-9]|30))T(([01][0-9]|2[0-3]):[0-5][0-9])Z)|(([13579][26][02468][048]|[13579][01345789](0)[48]|[13579][01345789][2468][048]|[02468][048][02468][048]|[02468][1235679](0)[48]|[02468][1235679][2468][048]|[0-9][0-9][13579][26])[\-](02)[\-](0[1-9]|1[0-9]|2[0-9])T(([01][0-9]|2[0-3]):[0-5][0-9])Z)|(([13579][26][02468][1235679]|[13579][01345789](0)[01235679]|[13579][01345789][2468][1235679]|[02468][048][02468][1235679]|[02468][1235679](0)[01235679]|[02468][1235679][2468][1235679]|[0-9][0-9][13579][01345789])[\-](02)[\-](0[1-9]|1[0-9]|2[0-8])T(([01][0-9]|2[0-3]):[0-5][0-9])Z))).</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.RegularExpressionAttribute(@"(((((20[0-9]{2})[\-](0[13578]|1[02])[\-](0[1-9]|[12][0-9]|3[01])|([0-9]{4})[\-]((0[469])|(11))[\-](0[1-9]|[12][0-9]|30))T(([01][0-9]|2[0-3]):[0-5][0-9])Z/)|(([13579][26][02468][048]|[13579][01345789](0)[48]|[13579][01345789][2468][048]|[02468][048][02468][048]|[02468][1235679](0)[48]|[02468][1235679][2468][048]|[0-9][0-9][13579][26])[\-](02)[\-](0[1-9]|1[0-9]|2[0-9])T(([01][0-9]|2[0-3]):[0-5][0-9])Z/)|(([13579][26][02468][1235679]|[13579][01345789](0)[01235679]|[13579][01345789][2468][1235679]|[02468][048][02468][1235679]|[02468][1235679](0)[01235679]|[02468][1235679][2468][1235679]|[0-9][0-9][13579][01345789])[\-](02)[\-](0[1-9]|1[0-9]|2[0-8])T(([01][0-9]|2[0-3]):[0-5][0-9])Z/))(((([0-9]{4})-(0[13578]|1[02])[\-](0[1-9]|[12][0-9]|3[01])|([0-9]{4})[\-]((0[469])|(11))[\-](0[1-9]|[12][0-9]|30))T(([01][0-9]|2[0-3]):[0-5][0-9])Z)|(([13579][26][02468][048]|[13579][01345789](0)[48]|[13579][01345789][2468][048]|[02468][048][02468][048]|[02468][1235679](0)[48]|[02468][1235679][2468][048]|[0-9][0-9][13579][26])[\-](02)[\-](0[1-9]|1[0-9]|2[0-9])T(([01][0-9]|2[0-3]):[0-5][0-9])Z)|(([13579][26][02468][1235679]|[13579][01345789](0)[01235679]|[13579][01345789][2468][1235679]|[02468][048][02468][1235679]|[02468][1235679](0)[01235679]|[02468][1235679][2468][1235679]|[0-9][0-9][13579][01345789])[\-](02)[\-](0[1-9]|1[0-9]|2[0-8])T(([01][0-9]|2[0-3]):[0-5][0-9])Z)))")]
        [System.Xml.Serialization.XmlElementAttribute("validityPeriod")]
        public string ValidityPeriod { get; set; }

        /// <summary>
        /// <para xml:lang="en">Maximum length: 35.</para>
        /// </summary>
        [System.ComponentModel.DataAnnotations.MaxLengthAttribute(35)]
        [System.Xml.Serialization.XmlElementAttribute("contractReference")]
        public string ContractReference { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("contractType")]
        public string ContractType { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("issuer_MarketParticipant.identification")]
        public PartyType Issuer_MarketParticipantPeriodIdentification { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("issuer_MarketParticipant.marketRole.code")]
        public string Issuer_MarketParticipantPeriodMarketRolePeriodCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("recipient_MarketParticipant.identification")]
        public PartyType Recipient_MarketParticipantPeriodIdentification { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("recipient_MarketParticipant.marketRole.code")]
        public string Recipient_MarketParticipantPeriodMarketRolePeriodCode { get; set; }

        [System.Xml.Serialization.XmlElementAttribute("applicationContext")]
        public LocationType ApplicationContext { get; set; }

        [System.Xml.Serialization.XmlIgnoreAttribute()]
        private System.Collections.ObjectModel.Collection<ConnectionPoint> _connectionPoint;

        [System.Xml.Serialization.XmlElementAttribute("ConnectionPoint")]
        public System.Collections.ObjectModel.Collection<ConnectionPoint> ConnectionPoint
        {
            get
            {
                return this._connectionPoint;
            }
            private set
            {
                this._connectionPoint = value;
            }
        }

        /// <summary>
        /// <para xml:lang="de">Initialisiert eine neue Instanz der <see cref="Nomination_Document" /> Klasse.</para>
        /// <para xml:lang="en">Initializes a new instance of the <see cref="Nomination_Document" /> class.</para>
        /// </summary>
        public Nomination_Document()
        {
            this._connectionPoint = new System.Collections.ObjectModel.Collection<ConnectionPoint>();
        }

        [System.Xml.Serialization.XmlAttributeAttribute("release")]
        public string Release { get; set; }
    }
}
